### ISSUE TITLE
Make navigation slide smoothly between pages

### ISSUE THREAD

**Issue by ckaiser258** [SnowpoolApp/native-front-end#6]
Navigation no longer sliding in between pages.

**Comment by matthewsedlacek** [comment]
Followed Instructions Found here: th3rdwave/react-native-safe-area-context#110

delete node_modules and your lockfile (package-lock.json / yarn.lock)
change the expo package version in package.json to 38.0.8
remove react-native-safe-area-context from your package.json
run yarn or npm install
run expo install react-native-safe-area-context
